name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE - ([#$NUMBER]($URL))'
template: |
  
  # Release Notes
  $CHANGES
  ---
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: 'Breaking Changes'
    label: 'BREAKING'
  - title: 'New'
    label: 
      - 'feature'
  - title: 'Changes'
    label:
      - 'enhancement'
  - title: 'Bug Fixes'
    label: 'bug'
  - title: 'Documentation'
    label: 'docs'
  - title: 'Other changes'
  - title: 'Dependency Updates'
    label: 'dependencies'
    collapse-after: 5

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'bug'
      - 'maintenance'
      - 'docs'
      - 'dependencies'
      - 'security'

exclude-labels:
  - 'skip-changelog'

replacers:
  - search: '/<!--.*?-->/gs' # Match and remove all Markdown comments.
    replace: ''
  - search: '(## Summary)\s*([\s\S]*?)\s*(## Release Notes)' # Match and remove summary and release note title
    replace: '$2'
  - search: '/^\n/gm' # Remove standalone newlines
    replace: ''
