name: Fetch Latest Release

on:
  workflow_dispatch:
    inputs:
      owner:
      repo:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch latest release
        run: |
          # Replace `owner/repo` with the repository you want to fetch from
          RELEASE=$(curl --silent "https://api.github.com/repos/${{inputs.owner}}/${{inputs.repo}}/releases/latest")

          # Extract the release body to a variable
          RELEASE_BODY=$(echo $RELEASE | jq -r .body)

          # Write the release body to a temporary file
          echo "$RELEASE_BODY" > temp.txt

          # Append the original file content to the temporary file
          cat latest_release.txt >> temp.txt

          # Replace the original file with the temporary file
          mv temp.txt latest_release.txt

      - name: Commit and push if it changed
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Update to latest release"
      - name: Create Pull Request
        run: |
          NEW_BRANCH="release_${{ inputs.owner }}_${{ inputs.repo }}_$(date +%s)"
          BASE_BRANCH="main"
          gh pr create -B ${BASE_BRANCH} -H ${NEW_BRANCH} --title "Merge ${NEW_BRANCH} into ${BASE_BRANCH}" --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


